#!/usr/bin/env python3

import sys
import frontmatter

try:
    b = frontmatter.load(sys.argv[1])
    functions = b['functions']
    print(",".join(functions))
except KeyError:
    print("ErrorParsing")
except TypeError:
    print("FunctionNameEmpty")